import { library } from '@fortawesome/fontawesome-svg-core'

import {
  faHospitalUser,
  faClipboardList,
  faHouseMedicalCircleExclamation,
  faMars,
  faVenus,
  faCalendar,
  faHospital,
  faUserNurse,
  faUserGear,
  faClipboardUser,
  faUserInjured,
  faUserDoctor,
  faArrowRight,
  faAngleRight,
  faHouse,
  faPen,
  faChartColumn,
  faChartLine,
  faGear,
  faCaretRight,
  faPlus,
  faMicrophone,
  faEllipsis,
  faMagnifyingGlass,
} from '@fortawesome/free-solid-svg-icons'

import { faCircleUser, faBell, faClock } from '@fortawesome/free-regular-svg-icons'

import { faWhatsapp } from '@fortawesome/free-brands-svg-icons'

library.add(
  faHospitalUser,
  faClipboardList,
  faHouseMedicalCircleExclamation,
  faMars,
  faVenus,
  faCalendar,
  faHospital,
  faUserNurse,
  faUserGear,
  faClipboardUser,
  faUserInjured,
  faUserDoctor,
  faCircleUser,
  faHouse,
  faArrowRight,
  faAngleRight,
  faPen,
  faChartColumn,
  faChartLine,
  faGear,
  faCaretRight,
  faPlus,
  faMicrophone,
  faEllipsis,
  faMagnifyingGlass,
  faBell,
  faClock,
  faWhatsapp,
)
